version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: "10.2.0"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: file list up
          command: ls -latr
      - run:
          name: make ignored ApiKeys.plist
          command: curl https://nyannyanengine-ios-d.firebaseapp.com/circleci/ApiKeys.plist > NyanNyanEngine/ApiKeys.plist
      - run:
          name: make ignored GoogleService.plist
          command: curl https://nyannyanengine-ios-d.firebaseapp.com/circleci/GoogleService-Info.plist > NyanNyanEngine/GoogleService-Info.plist
      - run:
          name: make ignored GoogleService-Release.plist
          command: curl https://nyannyanengine-ios-d.firebaseapp.com/circleci/GoogleService-Info.plist > NyanNyanEngine/GoogleService-Info-Release.plist
      - run:
          name: test
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone X
workflows:
  version: 2.1
  build:
    jobs:
      - build-and-test
